server:
  port: 8002
 
spring:
  application:
    name: user-provider
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200  
info: 
  app.name: user-provider
  build.artifactId: $project.artifactId$
  build.version: $project.verson$
  
mybatis: 
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.whp.vo
  mapper-locations: 
  - classpath:mybatis/mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://eureka:123@localhost:7001/eureka,http://eureka:123@localhost:7002