server:
  port: 7001
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka:123@localhost:7002/eureka
    register-with-eureka: false
    fetch-registry: false
 
security:
  basic:
    enabled: true
  user:
    name: eureka
    password: 123