server:
  port: 8080

spring:
  application:
    name: user-consume
eureka: 
  client: 
    service-url:
      defaultZone: http://eureka:123@localhost:7001/eureka,http://eureka:123@localhost:7002
    register-with-eureka: false
    
feign:
  hystrix: 
    enabled: true